// Code generated by Kitex v0.6.1. DO NOT EDIT.

package t1service

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	tft1 "kitex/test1/kitex_gen/test/tft1"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Tst(ctx context.Context, t1 *tft1.T1, callOptions ...callopt.Option) (r *tft1.T1, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kT1ServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kT1ServiceClient struct {
	*kClient
}

func (p *kT1ServiceClient) Tst(ctx context.Context, t1 *tft1.T1, callOptions ...callopt.Option) (r *tft1.T1, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Tst(ctx, t1)
}
