// Code generated by hertz generator.

package idlmanager

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _manageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addidlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _changeidlMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteidlMw() []app.HandlerFunc {
	// your code...
	return nil
}
