// Code generated by hertz generator.

package main

import (
	idlprovider "apigateway/IDLProvider"
	"net/http"
	_ "net/http/pprof" // injecting routing into http

	"github.com/cloudwego/hertz/pkg/app/server"
)

var idlDirPath = "./idl"
var svcPath = idlDirPath + "/svcPath"

func main() {
	go http.ListenAndServe("localhost:8083", nil)

	h := server.Default()

	register(h)
	idlprovider.LoadIDLContents(svcPath, idlDirPath)
	go idlprovider.WatchIDLFiles(idlDirPath)
	h.Spin()
}
