// Code generated by hertz generator.

package main

import (
	idlprovider "apigateway/IDLProvider"

	"github.com/cloudwego/hertz/pkg/app/server"
)

var idlDirPath = "./idl"
var svcPath = idlDirPath + "/svcPath"

func main() {
	h := server.Default()

	register(h)
	idlprovider.LoadIDLContents(svcPath, idlDirPath)
	go idlprovider.WatchIDLFiles(idlDirPath)
	h.Spin()
}
