// Code generated by Kitex v0.6.1. DO NOT EDIT.

package studentservice

import (
	"context"
	serverz "day3/kxS/client/kitex_gen/kitex/serverZ"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return studentServiceServiceInfo
}

var studentServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "StudentService"
	handlerType := (*serverz.StudentService)(nil)
	methods := map[string]kitex.MethodInfo{
		"Register": kitex.NewMethodInfo(registerHandler, newStudentServiceRegisterArgs, newStudentServiceRegisterResult, false),
		"Query":    kitex.NewMethodInfo(queryHandler, newStudentServiceQueryArgs, newStudentServiceQueryResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "serverz",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.1",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*serverz.StudentServiceRegisterArgs)
	realResult := result.(*serverz.StudentServiceRegisterResult)
	success, err := handler.(serverz.StudentService).Register(ctx, realArg.Student)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStudentServiceRegisterArgs() interface{} {
	return serverz.NewStudentServiceRegisterArgs()
}

func newStudentServiceRegisterResult() interface{} {
	return serverz.NewStudentServiceRegisterResult()
}

func queryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*serverz.StudentServiceQueryArgs)
	realResult := result.(*serverz.StudentServiceQueryResult)
	success, err := handler.(serverz.StudentService).Query(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStudentServiceQueryArgs() interface{} {
	return serverz.NewStudentServiceQueryArgs()
}

func newStudentServiceQueryResult() interface{} {
	return serverz.NewStudentServiceQueryResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, student *serverz.Student) (r *serverz.RegisterResp, err error) {
	var _args serverz.StudentServiceRegisterArgs
	_args.Student = student
	var _result serverz.StudentServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Query(ctx context.Context, req *serverz.QueryReq) (r *serverz.Student, err error) {
	var _args serverz.StudentServiceQueryArgs
	_args.Req = req
	var _result serverz.StudentServiceQueryResult
	if err = p.c.Call(ctx, "Query", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
