// Code generated by hertz generator.

package main

import (
	"api/idl_manager/biz/handler/idlmanager"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	idlmanager.Init()

	h := server.New(server.WithHostPorts("127.0.0.1:9100"))

	register(h)
	h.Spin()
}
