// Code generated by hertz generator.

package main

import (
	handler "apigateway/biz/handler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	r.POST("/api/:svc/:method", handler.ForwardPOST)
	r.GET("/api/:svc/:method", handler.ForwardGET)

	// your code ...
}
