// Code generated by hertz generator.

package idlmanager

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _manageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _changeserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listservicesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _setidlpathMw() []app.HandlerFunc {
	// your code...
	return nil
}
